// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: cart/cart.proto

package cart

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CartService service

type CartService interface {
	AddToCart(ctx context.Context, in *AddToCartRequest, opts ...client.CallOption) (*Cart, error)
	RemoveFromCart(ctx context.Context, in *RemoveFromCartRequest, opts ...client.CallOption) (*Cart, error)
	UpdateCartItem(ctx context.Context, in *UpdateCartItemRequest, opts ...client.CallOption) (*Cart, error)
	GetCart(ctx context.Context, in *GetCartRequest, opts ...client.CallOption) (*Cart, error)
	ClearCart(ctx context.Context, in *ClearCartRequest, opts ...client.CallOption) (*CommonResponse, error)
}

type cartService struct {
	c    client.Client
	name string
}

func NewCartService(name string, c client.Client) CartService {
	return &cartService{
		c:    c,
		name: name,
	}
}

func (c *cartService) AddToCart(ctx context.Context, in *AddToCartRequest, opts ...client.CallOption) (*Cart, error) {
	req := c.c.NewRequest(c.name, "CartService.AddToCart", in)
	out := new(Cart)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartService) RemoveFromCart(ctx context.Context, in *RemoveFromCartRequest, opts ...client.CallOption) (*Cart, error) {
	req := c.c.NewRequest(c.name, "CartService.RemoveFromCart", in)
	out := new(Cart)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartService) UpdateCartItem(ctx context.Context, in *UpdateCartItemRequest, opts ...client.CallOption) (*Cart, error) {
	req := c.c.NewRequest(c.name, "CartService.UpdateCartItem", in)
	out := new(Cart)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartService) GetCart(ctx context.Context, in *GetCartRequest, opts ...client.CallOption) (*Cart, error) {
	req := c.c.NewRequest(c.name, "CartService.GetCart", in)
	out := new(Cart)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartService) ClearCart(ctx context.Context, in *ClearCartRequest, opts ...client.CallOption) (*CommonResponse, error) {
	req := c.c.NewRequest(c.name, "CartService.ClearCart", in)
	out := new(CommonResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CartService service

type CartServiceHandler interface {
	AddToCart(context.Context, *AddToCartRequest, *Cart) error
	RemoveFromCart(context.Context, *RemoveFromCartRequest, *Cart) error
	UpdateCartItem(context.Context, *UpdateCartItemRequest, *Cart) error
	GetCart(context.Context, *GetCartRequest, *Cart) error
	ClearCart(context.Context, *ClearCartRequest, *CommonResponse) error
}

func RegisterCartServiceHandler(s server.Server, hdlr CartServiceHandler, opts ...server.HandlerOption) error {
	type cartService interface {
		AddToCart(ctx context.Context, in *AddToCartRequest, out *Cart) error
		RemoveFromCart(ctx context.Context, in *RemoveFromCartRequest, out *Cart) error
		UpdateCartItem(ctx context.Context, in *UpdateCartItemRequest, out *Cart) error
		GetCart(ctx context.Context, in *GetCartRequest, out *Cart) error
		ClearCart(ctx context.Context, in *ClearCartRequest, out *CommonResponse) error
	}
	type CartService struct {
		cartService
	}
	h := &cartServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CartService{h}, opts...))
}

type cartServiceHandler struct {
	CartServiceHandler
}

func (h *cartServiceHandler) AddToCart(ctx context.Context, in *AddToCartRequest, out *Cart) error {
	return h.CartServiceHandler.AddToCart(ctx, in, out)
}

func (h *cartServiceHandler) RemoveFromCart(ctx context.Context, in *RemoveFromCartRequest, out *Cart) error {
	return h.CartServiceHandler.RemoveFromCart(ctx, in, out)
}

func (h *cartServiceHandler) UpdateCartItem(ctx context.Context, in *UpdateCartItemRequest, out *Cart) error {
	return h.CartServiceHandler.UpdateCartItem(ctx, in, out)
}

func (h *cartServiceHandler) GetCart(ctx context.Context, in *GetCartRequest, out *Cart) error {
	return h.CartServiceHandler.GetCart(ctx, in, out)
}

func (h *cartServiceHandler) ClearCart(ctx context.Context, in *ClearCartRequest, out *CommonResponse) error {
	return h.CartServiceHandler.ClearCart(ctx, in, out)
}
