// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: ai/ai.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Context       string                 `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendRequest) Reset() {
	*x = RecommendRequest{}
	mi := &file_ai_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRequest) ProtoMessage() {}

func (x *RecommendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRequest.ProtoReflect.Descriptor instead.
func (*RecommendRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RecommendRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *RecommendRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type BookRecommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Score         float64                `protobuf:"fixed64,7,opt,name=score,proto3" json:"score,omitempty"`
	Reason        string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookRecommendation) Reset() {
	*x = BookRecommendation{}
	mi := &file_ai_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRecommendation) ProtoMessage() {}

func (x *BookRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRecommendation.ProtoReflect.Descriptor instead.
func (*BookRecommendation) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{1}
}

func (x *BookRecommendation) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *BookRecommendation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookRecommendation) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BookRecommendation) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *BookRecommendation) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BookRecommendation) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *BookRecommendation) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *BookRecommendation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RecommendResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*BookRecommendation  `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecommendResponse) Reset() {
	*x = RecommendResponse{}
	mi := &file_ai_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResponse) ProtoMessage() {}

func (x *RecommendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResponse.ProtoReflect.Descriptor instead.
func (*RecommendResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendResponse) GetRecommendations() []*BookRecommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

type ChatRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	UserId    uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message   string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SessionId string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// When the previous reply asked for HITL, resend the same message with these filled.
	HitlConfirmActionId string `protobuf:"bytes,4,opt,name=hitl_confirm_action_id,json=hitlConfirmActionId,proto3" json:"hitl_confirm_action_id,omitempty"`
	HitlConfirmSecret   string `protobuf:"bytes,5,opt,name=hitl_confirm_secret,json=hitlConfirmSecret,proto3" json:"hitl_confirm_secret,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_ai_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{3}
}

func (x *ChatRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetHitlConfirmActionId() string {
	if x != nil {
		return x.HitlConfirmActionId
	}
	return ""
}

func (x *ChatRequest) GetHitlConfirmSecret() string {
	if x != nil {
		return x.HitlConfirmSecret
	}
	return ""
}

type ChatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Reply          string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SuggestedBooks []*BookRecommendation  `protobuf:"bytes,3,rep,name=suggested_books,json=suggestedBooks,proto3" json:"suggested_books,omitempty"`
	Actions        []*ActionSuggestion    `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	HitlPending    bool                   `protobuf:"varint,5,opt,name=hitl_pending,json=hitlPending,proto3" json:"hitl_pending,omitempty"`
	HitlActionId   string                 `protobuf:"bytes,6,opt,name=hitl_action_id,json=hitlActionId,proto3" json:"hitl_action_id,omitempty"`
	HitlSecret     string                 `protobuf:"bytes,7,opt,name=hitl_secret,json=hitlSecret,proto3" json:"hitl_secret,omitempty"`
	HitlSummary    string                 `protobuf:"bytes,8,opt,name=hitl_summary,json=hitlSummary,proto3" json:"hitl_summary,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_ai_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{4}
}

func (x *ChatResponse) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *ChatResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatResponse) GetSuggestedBooks() []*BookRecommendation {
	if x != nil {
		return x.SuggestedBooks
	}
	return nil
}

func (x *ChatResponse) GetActions() []*ActionSuggestion {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ChatResponse) GetHitlPending() bool {
	if x != nil {
		return x.HitlPending
	}
	return false
}

func (x *ChatResponse) GetHitlActionId() string {
	if x != nil {
		return x.HitlActionId
	}
	return ""
}

func (x *ChatResponse) GetHitlSecret() string {
	if x != nil {
		return x.HitlSecret
	}
	return ""
}

func (x *ChatResponse) GetHitlSummary() string {
	if x != nil {
		return x.HitlSummary
	}
	return ""
}

type ActionSuggestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionSuggestion) Reset() {
	*x = ActionSuggestion{}
	mi := &file_ai_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSuggestion) ProtoMessage() {}

func (x *ActionSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSuggestion.ProtoReflect.Descriptor instead.
func (*ActionSuggestion) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{5}
}

func (x *ActionSuggestion) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ActionSuggestion) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ActionSuggestion) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// Streaming chat: server sends a sequence of chunks to the client.
//
//	type="delta"    → incremental text token
//	type="metadata" → session_id, suggested_books, actions (sent once at end)
//	type="error"    → error message
//	type="done"     → stream finished
type ChatStreamChunk struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Delta          string                 `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`
	SessionId      string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SuggestedBooks []*BookRecommendation  `protobuf:"bytes,4,rep,name=suggested_books,json=suggestedBooks,proto3" json:"suggested_books,omitempty"`
	Actions        []*ActionSuggestion    `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	Error          string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	HitlPending    bool                   `protobuf:"varint,7,opt,name=hitl_pending,json=hitlPending,proto3" json:"hitl_pending,omitempty"`
	HitlActionId   string                 `protobuf:"bytes,8,opt,name=hitl_action_id,json=hitlActionId,proto3" json:"hitl_action_id,omitempty"`
	HitlSecret     string                 `protobuf:"bytes,9,opt,name=hitl_secret,json=hitlSecret,proto3" json:"hitl_secret,omitempty"`
	HitlSummary    string                 `protobuf:"bytes,10,opt,name=hitl_summary,json=hitlSummary,proto3" json:"hitl_summary,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatStreamChunk) Reset() {
	*x = ChatStreamChunk{}
	mi := &file_ai_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamChunk) ProtoMessage() {}

func (x *ChatStreamChunk) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamChunk.ProtoReflect.Descriptor instead.
func (*ChatStreamChunk) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{6}
}

func (x *ChatStreamChunk) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatStreamChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *ChatStreamChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatStreamChunk) GetSuggestedBooks() []*BookRecommendation {
	if x != nil {
		return x.SuggestedBooks
	}
	return nil
}

func (x *ChatStreamChunk) GetActions() []*ActionSuggestion {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ChatStreamChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ChatStreamChunk) GetHitlPending() bool {
	if x != nil {
		return x.HitlPending
	}
	return false
}

func (x *ChatStreamChunk) GetHitlActionId() string {
	if x != nil {
		return x.HitlActionId
	}
	return ""
}

func (x *ChatStreamChunk) GetHitlSecret() string {
	if x != nil {
		return x.HitlSecret
	}
	return ""
}

func (x *ChatStreamChunk) GetHitlSummary() string {
	if x != nil {
		return x.HitlSummary
	}
	return ""
}

type SummaryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BookId          string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	ForceRegenerate bool                   `protobuf:"varint,2,opt,name=force_regenerate,json=forceRegenerate,proto3" json:"force_regenerate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SummaryRequest) Reset() {
	*x = SummaryRequest{}
	mi := &file_ai_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryRequest) ProtoMessage() {}

func (x *SummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryRequest.ProtoReflect.Descriptor instead.
func (*SummaryRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{7}
}

func (x *SummaryRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *SummaryRequest) GetForceRegenerate() bool {
	if x != nil {
		return x.ForceRegenerate
	}
	return false
}

type SummaryResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	BookId                string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Title                 string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary               string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	KeyThemes             []string               `protobuf:"bytes,4,rep,name=key_themes,json=keyThemes,proto3" json:"key_themes,omitempty"`
	TargetAudience        string                 `protobuf:"bytes,5,opt,name=target_audience,json=targetAudience,proto3" json:"target_audience,omitempty"`
	ReadingDifficulty     string                 `protobuf:"bytes,6,opt,name=reading_difficulty,json=readingDifficulty,proto3" json:"reading_difficulty,omitempty"`
	EstimatedReadingHours int32                  `protobuf:"varint,7,opt,name=estimated_reading_hours,json=estimatedReadingHours,proto3" json:"estimated_reading_hours,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SummaryResponse) Reset() {
	*x = SummaryResponse{}
	mi := &file_ai_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryResponse) ProtoMessage() {}

func (x *SummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryResponse.ProtoReflect.Descriptor instead.
func (*SummaryResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{8}
}

func (x *SummaryResponse) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *SummaryResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SummaryResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SummaryResponse) GetKeyThemes() []string {
	if x != nil {
		return x.KeyThemes
	}
	return nil
}

func (x *SummaryResponse) GetTargetAudience() string {
	if x != nil {
		return x.TargetAudience
	}
	return ""
}

func (x *SummaryResponse) GetReadingDifficulty() string {
	if x != nil {
		return x.ReadingDifficulty
	}
	return ""
}

func (x *SummaryResponse) GetEstimatedReadingHours() int32 {
	if x != nil {
		return x.EstimatedReadingHours
	}
	return 0
}

type SmartSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmartSearchRequest) Reset() {
	*x = SmartSearchRequest{}
	mi := &file_ai_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmartSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartSearchRequest) ProtoMessage() {}

func (x *SmartSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartSearchRequest.ProtoReflect.Descriptor instead.
func (*SmartSearchRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{9}
}

func (x *SmartSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SmartSearchRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SmartSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SmartSearchResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Results          []*BookRecommendation  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	InterpretedQuery string                 `protobuf:"bytes,2,opt,name=interpreted_query,json=interpretedQuery,proto3" json:"interpreted_query,omitempty"`
	ExtractedFilters map[string]string      `protobuf:"bytes,3,rep,name=extracted_filters,json=extractedFilters,proto3" json:"extracted_filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SmartSearchResponse) Reset() {
	*x = SmartSearchResponse{}
	mi := &file_ai_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmartSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmartSearchResponse) ProtoMessage() {}

func (x *SmartSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmartSearchResponse.ProtoReflect.Descriptor instead.
func (*SmartSearchResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{10}
}

func (x *SmartSearchResponse) GetResults() []*BookRecommendation {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SmartSearchResponse) GetInterpretedQuery() string {
	if x != nil {
		return x.InterpretedQuery
	}
	return ""
}

func (x *SmartSearchResponse) GetExtractedFilters() map[string]string {
	if x != nil {
		return x.ExtractedFilters
	}
	return nil
}

type TasteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TasteRequest) Reset() {
	*x = TasteRequest{}
	mi := &file_ai_ai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasteRequest) ProtoMessage() {}

func (x *TasteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasteRequest.ProtoReflect.Descriptor instead.
func (*TasteRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{11}
}

func (x *TasteRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type TasteResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopCategories        []string               `protobuf:"bytes,2,rep,name=top_categories,json=topCategories,proto3" json:"top_categories,omitempty"`
	TopAuthors           []string               `protobuf:"bytes,3,rep,name=top_authors,json=topAuthors,proto3" json:"top_authors,omitempty"`
	PersonalityTags      []string               `protobuf:"bytes,4,rep,name=personality_tags,json=personalityTags,proto3" json:"personality_tags,omitempty"`
	TasteSummary         string                 `protobuf:"bytes,5,opt,name=taste_summary,json=tasteSummary,proto3" json:"taste_summary,omitempty"`
	DiscoverySuggestions []*BookRecommendation  `protobuf:"bytes,6,rep,name=discovery_suggestions,json=discoverySuggestions,proto3" json:"discovery_suggestions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TasteResponse) Reset() {
	*x = TasteResponse{}
	mi := &file_ai_ai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasteResponse) ProtoMessage() {}

func (x *TasteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasteResponse.ProtoReflect.Descriptor instead.
func (*TasteResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{12}
}

func (x *TasteResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TasteResponse) GetTopCategories() []string {
	if x != nil {
		return x.TopCategories
	}
	return nil
}

func (x *TasteResponse) GetTopAuthors() []string {
	if x != nil {
		return x.TopAuthors
	}
	return nil
}

func (x *TasteResponse) GetPersonalityTags() []string {
	if x != nil {
		return x.PersonalityTags
	}
	return nil
}

func (x *TasteResponse) GetTasteSummary() string {
	if x != nil {
		return x.TasteSummary
	}
	return ""
}

func (x *TasteResponse) GetDiscoverySuggestions() []*BookRecommendation {
	if x != nil {
		return x.DiscoverySuggestions
	}
	return nil
}

type SimilarBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarBooksRequest) Reset() {
	*x = SimilarBooksRequest{}
	mi := &file_ai_ai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarBooksRequest) ProtoMessage() {}

func (x *SimilarBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarBooksRequest.ProtoReflect.Descriptor instead.
func (*SimilarBooksRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{13}
}

func (x *SimilarBooksRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *SimilarBooksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SimilarBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	SimilarBooks  []*BookRecommendation  `protobuf:"bytes,2,rep,name=similar_books,json=similarBooks,proto3" json:"similar_books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarBooksResponse) Reset() {
	*x = SimilarBooksResponse{}
	mi := &file_ai_ai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarBooksResponse) ProtoMessage() {}

func (x *SimilarBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarBooksResponse.ProtoReflect.Descriptor instead.
func (*SimilarBooksResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{14}
}

func (x *SimilarBooksResponse) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *SimilarBooksResponse) GetSimilarBooks() []*BookRecommendation {
	if x != nil {
		return x.SimilarBooks
	}
	return nil
}

type BackfillEmbeddingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When true, re-embed even if the vector store already has this book_id.
	Force bool `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	// 0: full scan in a background goroutine (RPC returns immediately).
	// >0: run synchronously in this call and stop after at most this many successful embeddings (smoke test).
	SyncLimit int32 `protobuf:"varint,2,opt,name=sync_limit,json=syncLimit,proto3" json:"sync_limit,omitempty"`
	// Abort after this many failures (HasEmbedding / OpenAI / upsert). 0 = default 200.
	MaxErrors     int32 `protobuf:"varint,3,opt,name=max_errors,json=maxErrors,proto3" json:"max_errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfillEmbeddingsRequest) Reset() {
	*x = BackfillEmbeddingsRequest{}
	mi := &file_ai_ai_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillEmbeddingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillEmbeddingsRequest) ProtoMessage() {}

func (x *BackfillEmbeddingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillEmbeddingsRequest.ProtoReflect.Descriptor instead.
func (*BackfillEmbeddingsRequest) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{15}
}

func (x *BackfillEmbeddingsRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *BackfillEmbeddingsRequest) GetSyncLimit() int32 {
	if x != nil {
		return x.SyncLimit
	}
	return 0
}

func (x *BackfillEmbeddingsRequest) GetMaxErrors() int32 {
	if x != nil {
		return x.MaxErrors
	}
	return 0
}

type BackfillEmbeddingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Background    bool                   `protobuf:"varint,1,opt,name=background,proto3" json:"background,omitempty"`
	Embedded      int32                  `protobuf:"varint,2,opt,name=embedded,proto3" json:"embedded,omitempty"`
	Skipped       int32                  `protobuf:"varint,3,opt,name=skipped,proto3" json:"skipped,omitempty"`
	Errors        int32                  `protobuf:"varint,4,opt,name=errors,proto3" json:"errors,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfillEmbeddingsResponse) Reset() {
	*x = BackfillEmbeddingsResponse{}
	mi := &file_ai_ai_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillEmbeddingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillEmbeddingsResponse) ProtoMessage() {}

func (x *BackfillEmbeddingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_ai_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillEmbeddingsResponse.ProtoReflect.Descriptor instead.
func (*BackfillEmbeddingsResponse) Descriptor() ([]byte, []int) {
	return file_ai_ai_proto_rawDescGZIP(), []int{16}
}

func (x *BackfillEmbeddingsResponse) GetBackground() bool {
	if x != nil {
		return x.Background
	}
	return false
}

func (x *BackfillEmbeddingsResponse) GetEmbedded() int32 {
	if x != nil {
		return x.Embedded
	}
	return 0
}

func (x *BackfillEmbeddingsResponse) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

func (x *BackfillEmbeddingsResponse) GetErrors() int32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *BackfillEmbeddingsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ai_ai_proto protoreflect.FileDescriptor

const file_ai_ai_proto_rawDesc = "" +
	"\n" +
	"\vai/ai.proto\x12\x02ai\"[\n" +
	"\x10RecommendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xd8\x01\n" +
	"\x12BookRecommendation\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x14\n" +
	"\x05score\x18\a \x01(\x01R\x05score\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\"U\n" +
	"\x11RecommendResponse\x12@\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x16.ai.BookRecommendationR\x0frecommendations\"\xc4\x01\n" +
	"\vChatRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x123\n" +
	"\x16hitl_confirm_action_id\x18\x04 \x01(\tR\x13hitlConfirmActionId\x12.\n" +
	"\x13hitl_confirm_secret\x18\x05 \x01(\tR\x11hitlConfirmSecret\"\xc1\x02\n" +
	"\fChatResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12?\n" +
	"\x0fsuggested_books\x18\x03 \x03(\v2\x16.ai.BookRecommendationR\x0esuggestedBooks\x12.\n" +
	"\aactions\x18\x04 \x03(\v2\x14.ai.ActionSuggestionR\aactions\x12!\n" +
	"\fhitl_pending\x18\x05 \x01(\bR\vhitlPending\x12$\n" +
	"\x0ehitl_action_id\x18\x06 \x01(\tR\fhitlActionId\x12\x1f\n" +
	"\vhitl_secret\x18\a \x01(\tR\n" +
	"hitlSecret\x12!\n" +
	"\fhitl_summary\x18\b \x01(\tR\vhitlSummary\"V\n" +
	"\x10ActionSuggestion\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"\xee\x02\n" +
	"\x0fChatStreamChunk\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\tR\x05delta\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12?\n" +
	"\x0fsuggested_books\x18\x04 \x03(\v2\x16.ai.BookRecommendationR\x0esuggestedBooks\x12.\n" +
	"\aactions\x18\x05 \x03(\v2\x14.ai.ActionSuggestionR\aactions\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12!\n" +
	"\fhitl_pending\x18\a \x01(\bR\vhitlPending\x12$\n" +
	"\x0ehitl_action_id\x18\b \x01(\tR\fhitlActionId\x12\x1f\n" +
	"\vhitl_secret\x18\t \x01(\tR\n" +
	"hitlSecret\x12!\n" +
	"\fhitl_summary\x18\n" +
	" \x01(\tR\vhitlSummary\"T\n" +
	"\x0eSummaryRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12)\n" +
	"\x10force_regenerate\x18\x02 \x01(\bR\x0fforceRegenerate\"\x89\x02\n" +
	"\x0fSummaryResponse\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"key_themes\x18\x04 \x03(\tR\tkeyThemes\x12'\n" +
	"\x0ftarget_audience\x18\x05 \x01(\tR\x0etargetAudience\x12-\n" +
	"\x12reading_difficulty\x18\x06 \x01(\tR\x11readingDifficulty\x126\n" +
	"\x17estimated_reading_hours\x18\a \x01(\x05R\x15estimatedReadingHours\"Y\n" +
	"\x12SmartSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x95\x02\n" +
	"\x13SmartSearchResponse\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.ai.BookRecommendationR\aresults\x12+\n" +
	"\x11interpreted_query\x18\x02 \x01(\tR\x10interpretedQuery\x12Z\n" +
	"\x11extracted_filters\x18\x03 \x03(\v2-.ai.SmartSearchResponse.ExtractedFiltersEntryR\x10extractedFilters\x1aC\n" +
	"\x15ExtractedFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\fTasteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"\x8d\x02\n" +
	"\rTasteResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12%\n" +
	"\x0etop_categories\x18\x02 \x03(\tR\rtopCategories\x12\x1f\n" +
	"\vtop_authors\x18\x03 \x03(\tR\n" +
	"topAuthors\x12)\n" +
	"\x10personality_tags\x18\x04 \x03(\tR\x0fpersonalityTags\x12#\n" +
	"\rtaste_summary\x18\x05 \x01(\tR\ftasteSummary\x12K\n" +
	"\x15discovery_suggestions\x18\x06 \x03(\v2\x16.ai.BookRecommendationR\x14discoverySuggestions\"D\n" +
	"\x13SimilarBooksRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"l\n" +
	"\x14SimilarBooksResponse\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12;\n" +
	"\rsimilar_books\x18\x02 \x03(\v2\x16.ai.BookRecommendationR\fsimilarBooks\"o\n" +
	"\x19BackfillEmbeddingsRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\x12\x1d\n" +
	"\n" +
	"sync_limit\x18\x02 \x01(\x05R\tsyncLimit\x12\x1d\n" +
	"\n" +
	"max_errors\x18\x03 \x01(\x05R\tmaxErrors\"\xa4\x01\n" +
	"\x1aBackfillEmbeddingsResponse\x12\x1e\n" +
	"\n" +
	"background\x18\x01 \x01(\bR\n" +
	"background\x12\x1a\n" +
	"\bembedded\x18\x02 \x01(\x05R\bembedded\x12\x18\n" +
	"\askipped\x18\x03 \x01(\x05R\askipped\x12\x16\n" +
	"\x06errors\x18\x04 \x01(\x05R\x06errors\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage2\x93\x04\n" +
	"\tAIService\x12A\n" +
	"\x12GetRecommendations\x12\x14.ai.RecommendRequest\x1a\x15.ai.RecommendResponse\x126\n" +
	"\x11ChatWithLibrarian\x12\x0f.ai.ChatRequest\x1a\x10.ai.ChatResponse\x124\n" +
	"\n" +
	"StreamChat\x12\x0f.ai.ChatRequest\x1a\x13.ai.ChatStreamChunk0\x01\x12>\n" +
	"\x13GenerateBookSummary\x12\x12.ai.SummaryRequest\x1a\x13.ai.SummaryResponse\x12>\n" +
	"\vSmartSearch\x12\x16.ai.SmartSearchRequest\x1a\x17.ai.SmartSearchResponse\x12:\n" +
	"\x13AnalyzeReadingTaste\x12\x10.ai.TasteRequest\x1a\x11.ai.TasteResponse\x12D\n" +
	"\x0fGetSimilarBooks\x12\x17.ai.SimilarBooksRequest\x1a\x18.ai.SimilarBooksResponse\x12S\n" +
	"\x12BackfillEmbeddings\x12\x1d.ai.BackfillEmbeddingsRequest\x1a\x1e.ai.BackfillEmbeddingsResponseB2Z0github.com/qiwang/book-e-commerce-micro/proto/aib\x06proto3"

var (
	file_ai_ai_proto_rawDescOnce sync.Once
	file_ai_ai_proto_rawDescData []byte
)

func file_ai_ai_proto_rawDescGZIP() []byte {
	file_ai_ai_proto_rawDescOnce.Do(func() {
		file_ai_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_ai_proto_rawDesc), len(file_ai_ai_proto_rawDesc)))
	})
	return file_ai_ai_proto_rawDescData
}

var file_ai_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_ai_ai_proto_goTypes = []any{
	(*RecommendRequest)(nil),           // 0: ai.RecommendRequest
	(*BookRecommendation)(nil),         // 1: ai.BookRecommendation
	(*RecommendResponse)(nil),          // 2: ai.RecommendResponse
	(*ChatRequest)(nil),                // 3: ai.ChatRequest
	(*ChatResponse)(nil),               // 4: ai.ChatResponse
	(*ActionSuggestion)(nil),           // 5: ai.ActionSuggestion
	(*ChatStreamChunk)(nil),            // 6: ai.ChatStreamChunk
	(*SummaryRequest)(nil),             // 7: ai.SummaryRequest
	(*SummaryResponse)(nil),            // 8: ai.SummaryResponse
	(*SmartSearchRequest)(nil),         // 9: ai.SmartSearchRequest
	(*SmartSearchResponse)(nil),        // 10: ai.SmartSearchResponse
	(*TasteRequest)(nil),               // 11: ai.TasteRequest
	(*TasteResponse)(nil),              // 12: ai.TasteResponse
	(*SimilarBooksRequest)(nil),        // 13: ai.SimilarBooksRequest
	(*SimilarBooksResponse)(nil),       // 14: ai.SimilarBooksResponse
	(*BackfillEmbeddingsRequest)(nil),  // 15: ai.BackfillEmbeddingsRequest
	(*BackfillEmbeddingsResponse)(nil), // 16: ai.BackfillEmbeddingsResponse
	nil,                                // 17: ai.SmartSearchResponse.ExtractedFiltersEntry
}
var file_ai_ai_proto_depIdxs = []int32{
	1,  // 0: ai.RecommendResponse.recommendations:type_name -> ai.BookRecommendation
	1,  // 1: ai.ChatResponse.suggested_books:type_name -> ai.BookRecommendation
	5,  // 2: ai.ChatResponse.actions:type_name -> ai.ActionSuggestion
	1,  // 3: ai.ChatStreamChunk.suggested_books:type_name -> ai.BookRecommendation
	5,  // 4: ai.ChatStreamChunk.actions:type_name -> ai.ActionSuggestion
	1,  // 5: ai.SmartSearchResponse.results:type_name -> ai.BookRecommendation
	17, // 6: ai.SmartSearchResponse.extracted_filters:type_name -> ai.SmartSearchResponse.ExtractedFiltersEntry
	1,  // 7: ai.TasteResponse.discovery_suggestions:type_name -> ai.BookRecommendation
	1,  // 8: ai.SimilarBooksResponse.similar_books:type_name -> ai.BookRecommendation
	0,  // 9: ai.AIService.GetRecommendations:input_type -> ai.RecommendRequest
	3,  // 10: ai.AIService.ChatWithLibrarian:input_type -> ai.ChatRequest
	3,  // 11: ai.AIService.StreamChat:input_type -> ai.ChatRequest
	7,  // 12: ai.AIService.GenerateBookSummary:input_type -> ai.SummaryRequest
	9,  // 13: ai.AIService.SmartSearch:input_type -> ai.SmartSearchRequest
	11, // 14: ai.AIService.AnalyzeReadingTaste:input_type -> ai.TasteRequest
	13, // 15: ai.AIService.GetSimilarBooks:input_type -> ai.SimilarBooksRequest
	15, // 16: ai.AIService.BackfillEmbeddings:input_type -> ai.BackfillEmbeddingsRequest
	2,  // 17: ai.AIService.GetRecommendations:output_type -> ai.RecommendResponse
	4,  // 18: ai.AIService.ChatWithLibrarian:output_type -> ai.ChatResponse
	6,  // 19: ai.AIService.StreamChat:output_type -> ai.ChatStreamChunk
	8,  // 20: ai.AIService.GenerateBookSummary:output_type -> ai.SummaryResponse
	10, // 21: ai.AIService.SmartSearch:output_type -> ai.SmartSearchResponse
	12, // 22: ai.AIService.AnalyzeReadingTaste:output_type -> ai.TasteResponse
	14, // 23: ai.AIService.GetSimilarBooks:output_type -> ai.SimilarBooksResponse
	16, // 24: ai.AIService.BackfillEmbeddings:output_type -> ai.BackfillEmbeddingsResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_ai_ai_proto_init() }
func file_ai_ai_proto_init() {
	if File_ai_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_ai_proto_rawDesc), len(file_ai_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_ai_proto_goTypes,
		DependencyIndexes: file_ai_ai_proto_depIdxs,
		MessageInfos:      file_ai_ai_proto_msgTypes,
	}.Build()
	File_ai_ai_proto = out.File
	file_ai_ai_proto_goTypes = nil
	file_ai_ai_proto_depIdxs = nil
}
