// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: ai/ai.proto

package ai

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AIService service

type AIService interface {
	GetRecommendations(ctx context.Context, in *RecommendRequest, opts ...client.CallOption) (*RecommendResponse, error)
	ChatWithLibrarian(ctx context.Context, in *ChatRequest, opts ...client.CallOption) (*ChatResponse, error)
	StreamChat(ctx context.Context, in *ChatRequest, opts ...client.CallOption) (AIService_StreamChatService, error)
	GenerateBookSummary(ctx context.Context, in *SummaryRequest, opts ...client.CallOption) (*SummaryResponse, error)
	SmartSearch(ctx context.Context, in *SmartSearchRequest, opts ...client.CallOption) (*SmartSearchResponse, error)
	AnalyzeReadingTaste(ctx context.Context, in *TasteRequest, opts ...client.CallOption) (*TasteResponse, error)
	GetSimilarBooks(ctx context.Context, in *SimilarBooksRequest, opts ...client.CallOption) (*SimilarBooksResponse, error)
	// Scan BookService for books missing vectors (or all if force) and upsert into the vector DB.
	BackfillEmbeddings(ctx context.Context, in *BackfillEmbeddingsRequest, opts ...client.CallOption) (*BackfillEmbeddingsResponse, error)
}

type aIService struct {
	c    client.Client
	name string
}

func NewAIService(name string, c client.Client) AIService {
	return &aIService{
		c:    c,
		name: name,
	}
}

func (c *aIService) GetRecommendations(ctx context.Context, in *RecommendRequest, opts ...client.CallOption) (*RecommendResponse, error) {
	req := c.c.NewRequest(c.name, "AIService.GetRecommendations", in)
	out := new(RecommendResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIService) ChatWithLibrarian(ctx context.Context, in *ChatRequest, opts ...client.CallOption) (*ChatResponse, error) {
	req := c.c.NewRequest(c.name, "AIService.ChatWithLibrarian", in)
	out := new(ChatResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIService) StreamChat(ctx context.Context, in *ChatRequest, opts ...client.CallOption) (AIService_StreamChatService, error) {
	req := c.c.NewRequest(c.name, "AIService.StreamChat", &ChatRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &aIServiceStreamChat{stream}, nil
}

type AIService_StreamChatService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ChatStreamChunk, error)
}

type aIServiceStreamChat struct {
	stream client.Stream
}

func (x *aIServiceStreamChat) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *aIServiceStreamChat) Close() error {
	return x.stream.Close()
}

func (x *aIServiceStreamChat) Context() context.Context {
	return x.stream.Context()
}

func (x *aIServiceStreamChat) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *aIServiceStreamChat) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *aIServiceStreamChat) Recv() (*ChatStreamChunk, error) {
	m := new(ChatStreamChunk)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aIService) GenerateBookSummary(ctx context.Context, in *SummaryRequest, opts ...client.CallOption) (*SummaryResponse, error) {
	req := c.c.NewRequest(c.name, "AIService.GenerateBookSummary", in)
	out := new(SummaryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIService) SmartSearch(ctx context.Context, in *SmartSearchRequest, opts ...client.CallOption) (*SmartSearchResponse, error) {
	req := c.c.NewRequest(c.name, "AIService.SmartSearch", in)
	out := new(SmartSearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIService) AnalyzeReadingTaste(ctx context.Context, in *TasteRequest, opts ...client.CallOption) (*TasteResponse, error) {
	req := c.c.NewRequest(c.name, "AIService.AnalyzeReadingTaste", in)
	out := new(TasteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIService) GetSimilarBooks(ctx context.Context, in *SimilarBooksRequest, opts ...client.CallOption) (*SimilarBooksResponse, error) {
	req := c.c.NewRequest(c.name, "AIService.GetSimilarBooks", in)
	out := new(SimilarBooksResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIService) BackfillEmbeddings(ctx context.Context, in *BackfillEmbeddingsRequest, opts ...client.CallOption) (*BackfillEmbeddingsResponse, error) {
	req := c.c.NewRequest(c.name, "AIService.BackfillEmbeddings", in)
	out := new(BackfillEmbeddingsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AIService service

type AIServiceHandler interface {
	GetRecommendations(context.Context, *RecommendRequest, *RecommendResponse) error
	ChatWithLibrarian(context.Context, *ChatRequest, *ChatResponse) error
	StreamChat(context.Context, *ChatRequest, AIService_StreamChatStream) error
	GenerateBookSummary(context.Context, *SummaryRequest, *SummaryResponse) error
	SmartSearch(context.Context, *SmartSearchRequest, *SmartSearchResponse) error
	AnalyzeReadingTaste(context.Context, *TasteRequest, *TasteResponse) error
	GetSimilarBooks(context.Context, *SimilarBooksRequest, *SimilarBooksResponse) error
	// Scan BookService for books missing vectors (or all if force) and upsert into the vector DB.
	BackfillEmbeddings(context.Context, *BackfillEmbeddingsRequest, *BackfillEmbeddingsResponse) error
}

func RegisterAIServiceHandler(s server.Server, hdlr AIServiceHandler, opts ...server.HandlerOption) error {
	type aIService interface {
		GetRecommendations(ctx context.Context, in *RecommendRequest, out *RecommendResponse) error
		ChatWithLibrarian(ctx context.Context, in *ChatRequest, out *ChatResponse) error
		StreamChat(ctx context.Context, stream server.Stream) error
		GenerateBookSummary(ctx context.Context, in *SummaryRequest, out *SummaryResponse) error
		SmartSearch(ctx context.Context, in *SmartSearchRequest, out *SmartSearchResponse) error
		AnalyzeReadingTaste(ctx context.Context, in *TasteRequest, out *TasteResponse) error
		GetSimilarBooks(ctx context.Context, in *SimilarBooksRequest, out *SimilarBooksResponse) error
		BackfillEmbeddings(ctx context.Context, in *BackfillEmbeddingsRequest, out *BackfillEmbeddingsResponse) error
	}
	type AIService struct {
		aIService
	}
	h := &aIServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AIService{h}, opts...))
}

type aIServiceHandler struct {
	AIServiceHandler
}

func (h *aIServiceHandler) GetRecommendations(ctx context.Context, in *RecommendRequest, out *RecommendResponse) error {
	return h.AIServiceHandler.GetRecommendations(ctx, in, out)
}

func (h *aIServiceHandler) ChatWithLibrarian(ctx context.Context, in *ChatRequest, out *ChatResponse) error {
	return h.AIServiceHandler.ChatWithLibrarian(ctx, in, out)
}

func (h *aIServiceHandler) StreamChat(ctx context.Context, stream server.Stream) error {
	m := new(ChatRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.AIServiceHandler.StreamChat(ctx, m, &aIServiceStreamChatStream{stream})
}

type AIService_StreamChatStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ChatStreamChunk) error
}

type aIServiceStreamChatStream struct {
	stream server.Stream
}

func (x *aIServiceStreamChatStream) Close() error {
	return x.stream.Close()
}

func (x *aIServiceStreamChatStream) Context() context.Context {
	return x.stream.Context()
}

func (x *aIServiceStreamChatStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *aIServiceStreamChatStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *aIServiceStreamChatStream) Send(m *ChatStreamChunk) error {
	return x.stream.Send(m)
}

func (h *aIServiceHandler) GenerateBookSummary(ctx context.Context, in *SummaryRequest, out *SummaryResponse) error {
	return h.AIServiceHandler.GenerateBookSummary(ctx, in, out)
}

func (h *aIServiceHandler) SmartSearch(ctx context.Context, in *SmartSearchRequest, out *SmartSearchResponse) error {
	return h.AIServiceHandler.SmartSearch(ctx, in, out)
}

func (h *aIServiceHandler) AnalyzeReadingTaste(ctx context.Context, in *TasteRequest, out *TasteResponse) error {
	return h.AIServiceHandler.AnalyzeReadingTaste(ctx, in, out)
}

func (h *aIServiceHandler) GetSimilarBooks(ctx context.Context, in *SimilarBooksRequest, out *SimilarBooksResponse) error {
	return h.AIServiceHandler.GetSimilarBooks(ctx, in, out)
}

func (h *aIServiceHandler) BackfillEmbeddings(ctx context.Context, in *BackfillEmbeddingsRequest, out *BackfillEmbeddingsResponse) error {
	return h.AIServiceHandler.BackfillEmbeddings(ctx, in, out)
}
