// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: store/store.proto

package store

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for StoreService service

type StoreService interface {
	ListStores(ctx context.Context, in *ListStoresRequest, opts ...client.CallOption) (*StoreListResponse, error)
	GetStoreDetail(ctx context.Context, in *GetStoreDetailRequest, opts ...client.CallOption) (*Store, error)
	GetNearestStore(ctx context.Context, in *GetNearestStoreRequest, opts ...client.CallOption) (*Store, error)
	GetStoresInRadius(ctx context.Context, in *GetStoresInRadiusRequest, opts ...client.CallOption) (*StoreListResponse, error)
	CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...client.CallOption) (*Store, error)
	UpdateStore(ctx context.Context, in *UpdateStoreRequest, opts ...client.CallOption) (*Store, error)
}

type storeService struct {
	c    client.Client
	name string
}

func NewStoreService(name string, c client.Client) StoreService {
	return &storeService{
		c:    c,
		name: name,
	}
}

func (c *storeService) ListStores(ctx context.Context, in *ListStoresRequest, opts ...client.CallOption) (*StoreListResponse, error) {
	req := c.c.NewRequest(c.name, "StoreService.ListStores", in)
	out := new(StoreListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeService) GetStoreDetail(ctx context.Context, in *GetStoreDetailRequest, opts ...client.CallOption) (*Store, error) {
	req := c.c.NewRequest(c.name, "StoreService.GetStoreDetail", in)
	out := new(Store)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeService) GetNearestStore(ctx context.Context, in *GetNearestStoreRequest, opts ...client.CallOption) (*Store, error) {
	req := c.c.NewRequest(c.name, "StoreService.GetNearestStore", in)
	out := new(Store)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeService) GetStoresInRadius(ctx context.Context, in *GetStoresInRadiusRequest, opts ...client.CallOption) (*StoreListResponse, error) {
	req := c.c.NewRequest(c.name, "StoreService.GetStoresInRadius", in)
	out := new(StoreListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeService) CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...client.CallOption) (*Store, error) {
	req := c.c.NewRequest(c.name, "StoreService.CreateStore", in)
	out := new(Store)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeService) UpdateStore(ctx context.Context, in *UpdateStoreRequest, opts ...client.CallOption) (*Store, error) {
	req := c.c.NewRequest(c.name, "StoreService.UpdateStore", in)
	out := new(Store)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StoreService service

type StoreServiceHandler interface {
	ListStores(context.Context, *ListStoresRequest, *StoreListResponse) error
	GetStoreDetail(context.Context, *GetStoreDetailRequest, *Store) error
	GetNearestStore(context.Context, *GetNearestStoreRequest, *Store) error
	GetStoresInRadius(context.Context, *GetStoresInRadiusRequest, *StoreListResponse) error
	CreateStore(context.Context, *CreateStoreRequest, *Store) error
	UpdateStore(context.Context, *UpdateStoreRequest, *Store) error
}

func RegisterStoreServiceHandler(s server.Server, hdlr StoreServiceHandler, opts ...server.HandlerOption) error {
	type storeService interface {
		ListStores(ctx context.Context, in *ListStoresRequest, out *StoreListResponse) error
		GetStoreDetail(ctx context.Context, in *GetStoreDetailRequest, out *Store) error
		GetNearestStore(ctx context.Context, in *GetNearestStoreRequest, out *Store) error
		GetStoresInRadius(ctx context.Context, in *GetStoresInRadiusRequest, out *StoreListResponse) error
		CreateStore(ctx context.Context, in *CreateStoreRequest, out *Store) error
		UpdateStore(ctx context.Context, in *UpdateStoreRequest, out *Store) error
	}
	type StoreService struct {
		storeService
	}
	h := &storeServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&StoreService{h}, opts...))
}

type storeServiceHandler struct {
	StoreServiceHandler
}

func (h *storeServiceHandler) ListStores(ctx context.Context, in *ListStoresRequest, out *StoreListResponse) error {
	return h.StoreServiceHandler.ListStores(ctx, in, out)
}

func (h *storeServiceHandler) GetStoreDetail(ctx context.Context, in *GetStoreDetailRequest, out *Store) error {
	return h.StoreServiceHandler.GetStoreDetail(ctx, in, out)
}

func (h *storeServiceHandler) GetNearestStore(ctx context.Context, in *GetNearestStoreRequest, out *Store) error {
	return h.StoreServiceHandler.GetNearestStore(ctx, in, out)
}

func (h *storeServiceHandler) GetStoresInRadius(ctx context.Context, in *GetStoresInRadiusRequest, out *StoreListResponse) error {
	return h.StoreServiceHandler.GetStoresInRadius(ctx, in, out)
}

func (h *storeServiceHandler) CreateStore(ctx context.Context, in *CreateStoreRequest, out *Store) error {
	return h.StoreServiceHandler.CreateStore(ctx, in, out)
}

func (h *storeServiceHandler) UpdateStore(ctx context.Context, in *UpdateStoreRequest, out *Store) error {
	return h.StoreServiceHandler.UpdateStore(ctx, in, out)
}
