// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: inventory/inventory.proto

package inventory

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for InventoryService service

type InventoryService interface {
	CheckStock(ctx context.Context, in *CheckStockRequest, opts ...client.CallOption) (*StockInfo, error)
	BatchCheckStock(ctx context.Context, in *BatchCheckStockRequest, opts ...client.CallOption) (*BatchStockResponse, error)
	SetStock(ctx context.Context, in *SetStockRequest, opts ...client.CallOption) (*CommonResponse, error)
	LockStock(ctx context.Context, in *LockStockRequest, opts ...client.CallOption) (*LockStockResponse, error)
	ReleaseStock(ctx context.Context, in *ReleaseStockRequest, opts ...client.CallOption) (*CommonResponse, error)
	DeductStock(ctx context.Context, in *DeductStockRequest, opts ...client.CallOption) (*CommonResponse, error)
	GetStoreBooks(ctx context.Context, in *GetStoreBooksRequest, opts ...client.CallOption) (*StoreBookListResponse, error)
}

type inventoryService struct {
	c    client.Client
	name string
}

func NewInventoryService(name string, c client.Client) InventoryService {
	return &inventoryService{
		c:    c,
		name: name,
	}
}

func (c *inventoryService) CheckStock(ctx context.Context, in *CheckStockRequest, opts ...client.CallOption) (*StockInfo, error) {
	req := c.c.NewRequest(c.name, "InventoryService.CheckStock", in)
	out := new(StockInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryService) BatchCheckStock(ctx context.Context, in *BatchCheckStockRequest, opts ...client.CallOption) (*BatchStockResponse, error) {
	req := c.c.NewRequest(c.name, "InventoryService.BatchCheckStock", in)
	out := new(BatchStockResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryService) SetStock(ctx context.Context, in *SetStockRequest, opts ...client.CallOption) (*CommonResponse, error) {
	req := c.c.NewRequest(c.name, "InventoryService.SetStock", in)
	out := new(CommonResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryService) LockStock(ctx context.Context, in *LockStockRequest, opts ...client.CallOption) (*LockStockResponse, error) {
	req := c.c.NewRequest(c.name, "InventoryService.LockStock", in)
	out := new(LockStockResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryService) ReleaseStock(ctx context.Context, in *ReleaseStockRequest, opts ...client.CallOption) (*CommonResponse, error) {
	req := c.c.NewRequest(c.name, "InventoryService.ReleaseStock", in)
	out := new(CommonResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryService) DeductStock(ctx context.Context, in *DeductStockRequest, opts ...client.CallOption) (*CommonResponse, error) {
	req := c.c.NewRequest(c.name, "InventoryService.DeductStock", in)
	out := new(CommonResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryService) GetStoreBooks(ctx context.Context, in *GetStoreBooksRequest, opts ...client.CallOption) (*StoreBookListResponse, error) {
	req := c.c.NewRequest(c.name, "InventoryService.GetStoreBooks", in)
	out := new(StoreBookListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for InventoryService service

type InventoryServiceHandler interface {
	CheckStock(context.Context, *CheckStockRequest, *StockInfo) error
	BatchCheckStock(context.Context, *BatchCheckStockRequest, *BatchStockResponse) error
	SetStock(context.Context, *SetStockRequest, *CommonResponse) error
	LockStock(context.Context, *LockStockRequest, *LockStockResponse) error
	ReleaseStock(context.Context, *ReleaseStockRequest, *CommonResponse) error
	DeductStock(context.Context, *DeductStockRequest, *CommonResponse) error
	GetStoreBooks(context.Context, *GetStoreBooksRequest, *StoreBookListResponse) error
}

func RegisterInventoryServiceHandler(s server.Server, hdlr InventoryServiceHandler, opts ...server.HandlerOption) error {
	type inventoryService interface {
		CheckStock(ctx context.Context, in *CheckStockRequest, out *StockInfo) error
		BatchCheckStock(ctx context.Context, in *BatchCheckStockRequest, out *BatchStockResponse) error
		SetStock(ctx context.Context, in *SetStockRequest, out *CommonResponse) error
		LockStock(ctx context.Context, in *LockStockRequest, out *LockStockResponse) error
		ReleaseStock(ctx context.Context, in *ReleaseStockRequest, out *CommonResponse) error
		DeductStock(ctx context.Context, in *DeductStockRequest, out *CommonResponse) error
		GetStoreBooks(ctx context.Context, in *GetStoreBooksRequest, out *StoreBookListResponse) error
	}
	type InventoryService struct {
		inventoryService
	}
	h := &inventoryServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&InventoryService{h}, opts...))
}

type inventoryServiceHandler struct {
	InventoryServiceHandler
}

func (h *inventoryServiceHandler) CheckStock(ctx context.Context, in *CheckStockRequest, out *StockInfo) error {
	return h.InventoryServiceHandler.CheckStock(ctx, in, out)
}

func (h *inventoryServiceHandler) BatchCheckStock(ctx context.Context, in *BatchCheckStockRequest, out *BatchStockResponse) error {
	return h.InventoryServiceHandler.BatchCheckStock(ctx, in, out)
}

func (h *inventoryServiceHandler) SetStock(ctx context.Context, in *SetStockRequest, out *CommonResponse) error {
	return h.InventoryServiceHandler.SetStock(ctx, in, out)
}

func (h *inventoryServiceHandler) LockStock(ctx context.Context, in *LockStockRequest, out *LockStockResponse) error {
	return h.InventoryServiceHandler.LockStock(ctx, in, out)
}

func (h *inventoryServiceHandler) ReleaseStock(ctx context.Context, in *ReleaseStockRequest, out *CommonResponse) error {
	return h.InventoryServiceHandler.ReleaseStock(ctx, in, out)
}

func (h *inventoryServiceHandler) DeductStock(ctx context.Context, in *DeductStockRequest, out *CommonResponse) error {
	return h.InventoryServiceHandler.DeductStock(ctx, in, out)
}

func (h *inventoryServiceHandler) GetStoreBooks(ctx context.Context, in *GetStoreBooksRequest, out *StoreBookListResponse) error {
	return h.InventoryServiceHandler.GetStoreBooks(ctx, in, out)
}
