// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: inventory/inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       uint64                 `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStockRequest) Reset() {
	*x = CheckStockRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockRequest) ProtoMessage() {}

func (x *CheckStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStockRequest.ProtoReflect.Descriptor instead.
func (*CheckStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *CheckStockRequest) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *CheckStockRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type StockInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StoreId        uint64                 `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	BookId         string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Quantity       int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	LockedQuantity int32                  `protobuf:"varint,4,opt,name=locked_quantity,json=lockedQuantity,proto3" json:"locked_quantity,omitempty"`
	Available      int32                  `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	Price          float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StockInfo) Reset() {
	*x = StockInfo{}
	mi := &file_inventory_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockInfo) ProtoMessage() {}

func (x *StockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockInfo.ProtoReflect.Descriptor instead.
func (*StockInfo) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *StockInfo) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *StockInfo) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *StockInfo) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockInfo) GetLockedQuantity() int32 {
	if x != nil {
		return x.LockedQuantity
	}
	return 0
}

func (x *StockInfo) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *StockInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type BatchCheckStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       uint64                 `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	BookIds       []string               `protobuf:"bytes,2,rep,name=book_ids,json=bookIds,proto3" json:"book_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckStockRequest) Reset() {
	*x = BatchCheckStockRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckStockRequest) ProtoMessage() {}

func (x *BatchCheckStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckStockRequest.ProtoReflect.Descriptor instead.
func (*BatchCheckStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *BatchCheckStockRequest) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *BatchCheckStockRequest) GetBookIds() []string {
	if x != nil {
		return x.BookIds
	}
	return nil
}

type BatchStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockInfo           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStockResponse) Reset() {
	*x = BatchStockResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStockResponse) ProtoMessage() {}

func (x *BatchStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStockResponse.ProtoReflect.Descriptor instead.
func (*BatchStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *BatchStockResponse) GetItems() []*StockInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type SetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       uint64                 `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStockRequest) Reset() {
	*x = SetStockRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStockRequest) ProtoMessage() {}

func (x *SetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStockRequest.ProtoReflect.Descriptor instead.
func (*SetStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *SetStockRequest) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *SetStockRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *SetStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SetStockRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type LockStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       uint64                 `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockStockRequest) Reset() {
	*x = LockStockRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockStockRequest) ProtoMessage() {}

func (x *LockStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockStockRequest.ProtoReflect.Descriptor instead.
func (*LockStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *LockStockRequest) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *LockStockRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *LockStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type LockStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LockId        string                 `protobuf:"bytes,3,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockStockResponse) Reset() {
	*x = LockStockResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockStockResponse) ProtoMessage() {}

func (x *LockStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockStockResponse.ProtoReflect.Descriptor instead.
func (*LockStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *LockStockResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LockStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LockStockResponse) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

type ReleaseStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	StoreId       uint64                 `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockRequest) Reset() {
	*x = ReleaseStockRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockRequest) ProtoMessage() {}

func (x *ReleaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseStockRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *ReleaseStockRequest) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

type DeductStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockId        string                 `protobuf:"bytes,1,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	StoreId       uint64                 `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductStockRequest) Reset() {
	*x = DeductStockRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductStockRequest) ProtoMessage() {}

func (x *DeductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductStockRequest.ProtoReflect.Descriptor instead.
func (*DeductStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *DeductStockRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

func (x *DeductStockRequest) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

type GetStoreBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       uint64                 `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreBooksRequest) Reset() {
	*x = GetStoreBooksRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreBooksRequest) ProtoMessage() {}

func (x *GetStoreBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreBooksRequest.ProtoReflect.Descriptor instead.
func (*GetStoreBooksRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *GetStoreBooksRequest) GetStoreId() uint64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *GetStoreBooksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetStoreBooksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type StoreBookItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Available     int32                  `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreBookItem) Reset() {
	*x = StoreBookItem{}
	mi := &file_inventory_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreBookItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreBookItem) ProtoMessage() {}

func (x *StoreBookItem) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreBookItem.ProtoReflect.Descriptor instead.
func (*StoreBookItem) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *StoreBookItem) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *StoreBookItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StoreBookItem) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *StoreBookItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type StoreBookListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StoreBookItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreBookListResponse) Reset() {
	*x = StoreBookListResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreBookListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreBookListResponse) ProtoMessage() {}

func (x *StoreBookListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreBookListResponse.ProtoReflect.Descriptor instead.
func (*StoreBookListResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *StoreBookListResponse) GetItems() []*StoreBookItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *StoreBookListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *CommonResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_inventory_inventory_proto protoreflect.FileDescriptor

const file_inventory_inventory_proto_rawDesc = "" +
	"\n" +
	"\x19inventory/inventory.proto\x12\tinventory\"G\n" +
	"\x11CheckStockRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x04R\astoreId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\"\xb8\x01\n" +
	"\tStockInfo\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x04R\astoreId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12'\n" +
	"\x0flocked_quantity\x18\x04 \x01(\x05R\x0elockedQuantity\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\x05R\tavailable\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\"N\n" +
	"\x16BatchCheckStockRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x04R\astoreId\x12\x19\n" +
	"\bbook_ids\x18\x02 \x03(\tR\abookIds\"@\n" +
	"\x12BatchStockResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.inventory.StockInfoR\x05items\"w\n" +
	"\x0fSetStockRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x04R\astoreId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"b\n" +
	"\x10LockStockRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x04R\astoreId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"Z\n" +
	"\x11LockStockResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\alock_id\x18\x03 \x01(\tR\x06lockId\"I\n" +
	"\x13ReleaseStockRequest\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\x04R\astoreId\"H\n" +
	"\x12DeductStockRequest\x12\x17\n" +
	"\alock_id\x18\x01 \x01(\tR\x06lockId\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\x04R\astoreId\"b\n" +
	"\x14GetStoreBooksRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x04R\astoreId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"x\n" +
	"\rStoreBookItem\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\x05R\tavailable\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"]\n" +
	"\x15StoreBookListResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.inventory.StoreBookItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\">\n" +
	"\x0eCommonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9c\x04\n" +
	"\x10InventoryService\x12@\n" +
	"\n" +
	"CheckStock\x12\x1c.inventory.CheckStockRequest\x1a\x14.inventory.StockInfo\x12S\n" +
	"\x0fBatchCheckStock\x12!.inventory.BatchCheckStockRequest\x1a\x1d.inventory.BatchStockResponse\x12A\n" +
	"\bSetStock\x12\x1a.inventory.SetStockRequest\x1a\x19.inventory.CommonResponse\x12F\n" +
	"\tLockStock\x12\x1b.inventory.LockStockRequest\x1a\x1c.inventory.LockStockResponse\x12I\n" +
	"\fReleaseStock\x12\x1e.inventory.ReleaseStockRequest\x1a\x19.inventory.CommonResponse\x12G\n" +
	"\vDeductStock\x12\x1d.inventory.DeductStockRequest\x1a\x19.inventory.CommonResponse\x12R\n" +
	"\rGetStoreBooks\x12\x1f.inventory.GetStoreBooksRequest\x1a .inventory.StoreBookListResponseB9Z7github.com/qiwang/book-e-commerce-micro/proto/inventoryb\x06proto3"

var (
	file_inventory_inventory_proto_rawDescOnce sync.Once
	file_inventory_inventory_proto_rawDescData []byte
)

func file_inventory_inventory_proto_rawDescGZIP() []byte {
	file_inventory_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_inventory_proto_rawDesc), len(file_inventory_inventory_proto_rawDesc)))
	})
	return file_inventory_inventory_proto_rawDescData
}

var file_inventory_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_inventory_inventory_proto_goTypes = []any{
	(*CheckStockRequest)(nil),      // 0: inventory.CheckStockRequest
	(*StockInfo)(nil),              // 1: inventory.StockInfo
	(*BatchCheckStockRequest)(nil), // 2: inventory.BatchCheckStockRequest
	(*BatchStockResponse)(nil),     // 3: inventory.BatchStockResponse
	(*SetStockRequest)(nil),        // 4: inventory.SetStockRequest
	(*LockStockRequest)(nil),       // 5: inventory.LockStockRequest
	(*LockStockResponse)(nil),      // 6: inventory.LockStockResponse
	(*ReleaseStockRequest)(nil),    // 7: inventory.ReleaseStockRequest
	(*DeductStockRequest)(nil),     // 8: inventory.DeductStockRequest
	(*GetStoreBooksRequest)(nil),   // 9: inventory.GetStoreBooksRequest
	(*StoreBookItem)(nil),          // 10: inventory.StoreBookItem
	(*StoreBookListResponse)(nil),  // 11: inventory.StoreBookListResponse
	(*CommonResponse)(nil),         // 12: inventory.CommonResponse
}
var file_inventory_inventory_proto_depIdxs = []int32{
	1,  // 0: inventory.BatchStockResponse.items:type_name -> inventory.StockInfo
	10, // 1: inventory.StoreBookListResponse.items:type_name -> inventory.StoreBookItem
	0,  // 2: inventory.InventoryService.CheckStock:input_type -> inventory.CheckStockRequest
	2,  // 3: inventory.InventoryService.BatchCheckStock:input_type -> inventory.BatchCheckStockRequest
	4,  // 4: inventory.InventoryService.SetStock:input_type -> inventory.SetStockRequest
	5,  // 5: inventory.InventoryService.LockStock:input_type -> inventory.LockStockRequest
	7,  // 6: inventory.InventoryService.ReleaseStock:input_type -> inventory.ReleaseStockRequest
	8,  // 7: inventory.InventoryService.DeductStock:input_type -> inventory.DeductStockRequest
	9,  // 8: inventory.InventoryService.GetStoreBooks:input_type -> inventory.GetStoreBooksRequest
	1,  // 9: inventory.InventoryService.CheckStock:output_type -> inventory.StockInfo
	3,  // 10: inventory.InventoryService.BatchCheckStock:output_type -> inventory.BatchStockResponse
	12, // 11: inventory.InventoryService.SetStock:output_type -> inventory.CommonResponse
	6,  // 12: inventory.InventoryService.LockStock:output_type -> inventory.LockStockResponse
	12, // 13: inventory.InventoryService.ReleaseStock:output_type -> inventory.CommonResponse
	12, // 14: inventory.InventoryService.DeductStock:output_type -> inventory.CommonResponse
	11, // 15: inventory.InventoryService.GetStoreBooks:output_type -> inventory.StoreBookListResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_inventory_inventory_proto_init() }
func file_inventory_inventory_proto_init() {
	if File_inventory_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_inventory_proto_rawDesc), len(file_inventory_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_inventory_proto_msgTypes,
	}.Build()
	File_inventory_inventory_proto = out.File
	file_inventory_inventory_proto_goTypes = nil
	file_inventory_inventory_proto_depIdxs = nil
}
