// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: book/book.proto

package book

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for BookService service

type BookService interface {
	GetBookDetail(ctx context.Context, in *GetBookDetailRequest, opts ...client.CallOption) (*Book, error)
	GetBooksByIds(ctx context.Context, in *GetBooksByIdsRequest, opts ...client.CallOption) (*BookListResponse, error)
	SearchBooks(ctx context.Context, in *SearchBooksRequest, opts ...client.CallOption) (*BookListResponse, error)
	ListByCategory(ctx context.Context, in *ListByCategoryRequest, opts ...client.CallOption) (*BookListResponse, error)
	CreateBook(ctx context.Context, in *CreateBookRequest, opts ...client.CallOption) (*Book, error)
	UpdateBook(ctx context.Context, in *UpdateBookRequest, opts ...client.CallOption) (*Book, error)
	DeleteBook(ctx context.Context, in *DeleteBookRequest, opts ...client.CallOption) (*CommonResponse, error)
	ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...client.CallOption) (*CategoryListResponse, error)
}

type bookService struct {
	c    client.Client
	name string
}

func NewBookService(name string, c client.Client) BookService {
	return &bookService{
		c:    c,
		name: name,
	}
}

func (c *bookService) GetBookDetail(ctx context.Context, in *GetBookDetailRequest, opts ...client.CallOption) (*Book, error) {
	req := c.c.NewRequest(c.name, "BookService.GetBookDetail", in)
	out := new(Book)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookService) GetBooksByIds(ctx context.Context, in *GetBooksByIdsRequest, opts ...client.CallOption) (*BookListResponse, error) {
	req := c.c.NewRequest(c.name, "BookService.GetBooksByIds", in)
	out := new(BookListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookService) SearchBooks(ctx context.Context, in *SearchBooksRequest, opts ...client.CallOption) (*BookListResponse, error) {
	req := c.c.NewRequest(c.name, "BookService.SearchBooks", in)
	out := new(BookListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookService) ListByCategory(ctx context.Context, in *ListByCategoryRequest, opts ...client.CallOption) (*BookListResponse, error) {
	req := c.c.NewRequest(c.name, "BookService.ListByCategory", in)
	out := new(BookListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookService) CreateBook(ctx context.Context, in *CreateBookRequest, opts ...client.CallOption) (*Book, error) {
	req := c.c.NewRequest(c.name, "BookService.CreateBook", in)
	out := new(Book)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookService) UpdateBook(ctx context.Context, in *UpdateBookRequest, opts ...client.CallOption) (*Book, error) {
	req := c.c.NewRequest(c.name, "BookService.UpdateBook", in)
	out := new(Book)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookService) DeleteBook(ctx context.Context, in *DeleteBookRequest, opts ...client.CallOption) (*CommonResponse, error) {
	req := c.c.NewRequest(c.name, "BookService.DeleteBook", in)
	out := new(CommonResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookService) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...client.CallOption) (*CategoryListResponse, error) {
	req := c.c.NewRequest(c.name, "BookService.ListCategories", in)
	out := new(CategoryListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BookService service

type BookServiceHandler interface {
	GetBookDetail(context.Context, *GetBookDetailRequest, *Book) error
	GetBooksByIds(context.Context, *GetBooksByIdsRequest, *BookListResponse) error
	SearchBooks(context.Context, *SearchBooksRequest, *BookListResponse) error
	ListByCategory(context.Context, *ListByCategoryRequest, *BookListResponse) error
	CreateBook(context.Context, *CreateBookRequest, *Book) error
	UpdateBook(context.Context, *UpdateBookRequest, *Book) error
	DeleteBook(context.Context, *DeleteBookRequest, *CommonResponse) error
	ListCategories(context.Context, *ListCategoriesRequest, *CategoryListResponse) error
}

func RegisterBookServiceHandler(s server.Server, hdlr BookServiceHandler, opts ...server.HandlerOption) error {
	type bookService interface {
		GetBookDetail(ctx context.Context, in *GetBookDetailRequest, out *Book) error
		GetBooksByIds(ctx context.Context, in *GetBooksByIdsRequest, out *BookListResponse) error
		SearchBooks(ctx context.Context, in *SearchBooksRequest, out *BookListResponse) error
		ListByCategory(ctx context.Context, in *ListByCategoryRequest, out *BookListResponse) error
		CreateBook(ctx context.Context, in *CreateBookRequest, out *Book) error
		UpdateBook(ctx context.Context, in *UpdateBookRequest, out *Book) error
		DeleteBook(ctx context.Context, in *DeleteBookRequest, out *CommonResponse) error
		ListCategories(ctx context.Context, in *ListCategoriesRequest, out *CategoryListResponse) error
	}
	type BookService struct {
		bookService
	}
	h := &bookServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&BookService{h}, opts...))
}

type bookServiceHandler struct {
	BookServiceHandler
}

func (h *bookServiceHandler) GetBookDetail(ctx context.Context, in *GetBookDetailRequest, out *Book) error {
	return h.BookServiceHandler.GetBookDetail(ctx, in, out)
}

func (h *bookServiceHandler) GetBooksByIds(ctx context.Context, in *GetBooksByIdsRequest, out *BookListResponse) error {
	return h.BookServiceHandler.GetBooksByIds(ctx, in, out)
}

func (h *bookServiceHandler) SearchBooks(ctx context.Context, in *SearchBooksRequest, out *BookListResponse) error {
	return h.BookServiceHandler.SearchBooks(ctx, in, out)
}

func (h *bookServiceHandler) ListByCategory(ctx context.Context, in *ListByCategoryRequest, out *BookListResponse) error {
	return h.BookServiceHandler.ListByCategory(ctx, in, out)
}

func (h *bookServiceHandler) CreateBook(ctx context.Context, in *CreateBookRequest, out *Book) error {
	return h.BookServiceHandler.CreateBook(ctx, in, out)
}

func (h *bookServiceHandler) UpdateBook(ctx context.Context, in *UpdateBookRequest, out *Book) error {
	return h.BookServiceHandler.UpdateBook(ctx, in, out)
}

func (h *bookServiceHandler) DeleteBook(ctx context.Context, in *DeleteBookRequest, out *CommonResponse) error {
	return h.BookServiceHandler.DeleteBook(ctx, in, out)
}

func (h *bookServiceHandler) ListCategories(ctx context.Context, in *ListCategoriesRequest, out *CategoryListResponse) error {
	return h.BookServiceHandler.ListCategories(ctx, in, out)
}
