// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: order/order.proto

package order

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for OrderService service

type OrderService interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...client.CallOption) (*Order, error)
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...client.CallOption) (*Order, error)
	ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...client.CallOption) (*OrderListResponse, error)
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...client.CallOption) (*CommonResponse, error)
	UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusRequest, opts ...client.CallOption) (*CommonResponse, error)
}

type orderService struct {
	c    client.Client
	name string
}

func NewOrderService(name string, c client.Client) OrderService {
	return &orderService{
		c:    c,
		name: name,
	}
}

func (c *orderService) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...client.CallOption) (*Order, error) {
	req := c.c.NewRequest(c.name, "OrderService.CreateOrder", in)
	out := new(Order)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...client.CallOption) (*Order, error) {
	req := c.c.NewRequest(c.name, "OrderService.GetOrder", in)
	out := new(Order)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...client.CallOption) (*OrderListResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.ListOrders", in)
	out := new(OrderListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...client.CallOption) (*CommonResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.CancelOrder", in)
	out := new(CommonResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderService) UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusRequest, opts ...client.CallOption) (*CommonResponse, error) {
	req := c.c.NewRequest(c.name, "OrderService.UpdateOrderStatus", in)
	out := new(CommonResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrderService service

type OrderServiceHandler interface {
	CreateOrder(context.Context, *CreateOrderRequest, *Order) error
	GetOrder(context.Context, *GetOrderRequest, *Order) error
	ListOrders(context.Context, *ListOrdersRequest, *OrderListResponse) error
	CancelOrder(context.Context, *CancelOrderRequest, *CommonResponse) error
	UpdateOrderStatus(context.Context, *UpdateOrderStatusRequest, *CommonResponse) error
}

func RegisterOrderServiceHandler(s server.Server, hdlr OrderServiceHandler, opts ...server.HandlerOption) error {
	type orderService interface {
		CreateOrder(ctx context.Context, in *CreateOrderRequest, out *Order) error
		GetOrder(ctx context.Context, in *GetOrderRequest, out *Order) error
		ListOrders(ctx context.Context, in *ListOrdersRequest, out *OrderListResponse) error
		CancelOrder(ctx context.Context, in *CancelOrderRequest, out *CommonResponse) error
		UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusRequest, out *CommonResponse) error
	}
	type OrderService struct {
		orderService
	}
	h := &orderServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&OrderService{h}, opts...))
}

type orderServiceHandler struct {
	OrderServiceHandler
}

func (h *orderServiceHandler) CreateOrder(ctx context.Context, in *CreateOrderRequest, out *Order) error {
	return h.OrderServiceHandler.CreateOrder(ctx, in, out)
}

func (h *orderServiceHandler) GetOrder(ctx context.Context, in *GetOrderRequest, out *Order) error {
	return h.OrderServiceHandler.GetOrder(ctx, in, out)
}

func (h *orderServiceHandler) ListOrders(ctx context.Context, in *ListOrdersRequest, out *OrderListResponse) error {
	return h.OrderServiceHandler.ListOrders(ctx, in, out)
}

func (h *orderServiceHandler) CancelOrder(ctx context.Context, in *CancelOrderRequest, out *CommonResponse) error {
	return h.OrderServiceHandler.CancelOrder(ctx, in, out)
}

func (h *orderServiceHandler) UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusRequest, out *CommonResponse) error {
	return h.OrderServiceHandler.UpdateOrderStatus(ctx, in, out)
}
