// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: payment/payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreatePaymentRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type ProcessPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessPaymentRequest) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

type GetPaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentStatusRequest) Reset() {
	*x = GetPaymentStatusRequest{}
	mi := &file_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentStatusRequest) ProtoMessage() {}

func (x *GetPaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentStatusRequest) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

type RefundPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentNo     string                 `protobuf:"bytes,1,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentRequest) Reset() {
	*x = RefundPaymentRequest{}
	mi := &file_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentRequest) ProtoMessage() {}

func (x *RefundPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentRequest.ProtoReflect.Descriptor instead.
func (*RefundPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *RefundPaymentRequest) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *RefundPaymentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetPaymentByOrderIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentByOrderIdRequest) Reset() {
	*x = GetPaymentByOrderIdRequest{}
	mi := &file_payment_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByOrderIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByOrderIdRequest) ProtoMessage() {}

func (x *GetPaymentByOrderIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByOrderIdRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentByOrderIdRequest) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentByOrderIdRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentNo     string                 `protobuf:"bytes,2,opt,name=payment_no,json=paymentNo,proto3" json:"payment_no,omitempty"`
	OrderId       uint64                 `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Method        string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	PaidAt        string                 `protobuf:"bytes,8,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	RefundedAt    string                 `protobuf:"bytes,9,opt,name=refunded_at,json=refundedAt,proto3" json:"refunded_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payment_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{5}
}

func (x *Payment) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payment) GetPaymentNo() string {
	if x != nil {
		return x.PaymentNo
	}
	return ""
}

func (x *Payment) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Payment) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

func (x *Payment) GetRefundedAt() string {
	if x != nil {
		return x.RefundedAt
	}
	return ""
}

func (x *Payment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type PaymentResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Payment       *Payment               `protobuf:"bytes,3,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResult) Reset() {
	*x = PaymentResult{}
	mi := &file_payment_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResult) ProtoMessage() {}

func (x *PaymentResult) ProtoReflect() protoreflect.Message {
	mi := &file_payment_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResult.ProtoReflect.Descriptor instead.
func (*PaymentResult) Descriptor() ([]byte, []int) {
	return file_payment_payment_proto_rawDescGZIP(), []int{6}
}

func (x *PaymentResult) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PaymentResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PaymentResult) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

var File_payment_payment_proto protoreflect.FileDescriptor

const file_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x15payment/payment.proto\x12\apayment\"z\n" +
	"\x14CreatePaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\"6\n" +
	"\x15ProcessPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\"8\n" +
	"\x17GetPaymentStatusRequest\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\"M\n" +
	"\x14RefundPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x01 \x01(\tR\tpaymentNo\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"7\n" +
	"\x1aGetPaymentByOrderIdRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"\x8d\x02\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"payment_no\x18\x02 \x01(\tR\tpaymentNo\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x04R\aorderId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x17\n" +
	"\apaid_at\x18\b \x01(\tR\x06paidAt\x12\x1f\n" +
	"\vrefunded_at\x18\t \x01(\tR\n" +
	"refundedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"i\n" +
	"\rPaymentResult\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\apayment\x18\x03 \x01(\v2\x10.payment.PaymentR\apayment2\xfa\x02\n" +
	"\x0ePaymentService\x12@\n" +
	"\rCreatePayment\x12\x1d.payment.CreatePaymentRequest\x1a\x10.payment.Payment\x12H\n" +
	"\x0eProcessPayment\x12\x1e.payment.ProcessPaymentRequest\x1a\x16.payment.PaymentResult\x12F\n" +
	"\x10GetPaymentStatus\x12 .payment.GetPaymentStatusRequest\x1a\x10.payment.Payment\x12F\n" +
	"\rRefundPayment\x12\x1d.payment.RefundPaymentRequest\x1a\x16.payment.PaymentResult\x12L\n" +
	"\x13GetPaymentByOrderId\x12#.payment.GetPaymentByOrderIdRequest\x1a\x10.payment.PaymentB7Z5github.com/qiwang/book-e-commerce-micro/proto/paymentb\x06proto3"

var (
	file_payment_payment_proto_rawDescOnce sync.Once
	file_payment_payment_proto_rawDescData []byte
)

func file_payment_payment_proto_rawDescGZIP() []byte {
	file_payment_payment_proto_rawDescOnce.Do(func() {
		file_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_payment_proto_rawDesc), len(file_payment_payment_proto_rawDesc)))
	})
	return file_payment_payment_proto_rawDescData
}

var file_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_payment_payment_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil),       // 0: payment.CreatePaymentRequest
	(*ProcessPaymentRequest)(nil),      // 1: payment.ProcessPaymentRequest
	(*GetPaymentStatusRequest)(nil),    // 2: payment.GetPaymentStatusRequest
	(*RefundPaymentRequest)(nil),       // 3: payment.RefundPaymentRequest
	(*GetPaymentByOrderIdRequest)(nil), // 4: payment.GetPaymentByOrderIdRequest
	(*Payment)(nil),                    // 5: payment.Payment
	(*PaymentResult)(nil),              // 6: payment.PaymentResult
}
var file_payment_payment_proto_depIdxs = []int32{
	5, // 0: payment.PaymentResult.payment:type_name -> payment.Payment
	0, // 1: payment.PaymentService.CreatePayment:input_type -> payment.CreatePaymentRequest
	1, // 2: payment.PaymentService.ProcessPayment:input_type -> payment.ProcessPaymentRequest
	2, // 3: payment.PaymentService.GetPaymentStatus:input_type -> payment.GetPaymentStatusRequest
	3, // 4: payment.PaymentService.RefundPayment:input_type -> payment.RefundPaymentRequest
	4, // 5: payment.PaymentService.GetPaymentByOrderId:input_type -> payment.GetPaymentByOrderIdRequest
	5, // 6: payment.PaymentService.CreatePayment:output_type -> payment.Payment
	6, // 7: payment.PaymentService.ProcessPayment:output_type -> payment.PaymentResult
	5, // 8: payment.PaymentService.GetPaymentStatus:output_type -> payment.Payment
	6, // 9: payment.PaymentService.RefundPayment:output_type -> payment.PaymentResult
	5, // 10: payment.PaymentService.GetPaymentByOrderId:output_type -> payment.Payment
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_payment_payment_proto_init() }
func file_payment_payment_proto_init() {
	if File_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_payment_proto_rawDesc), len(file_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_payment_proto_goTypes,
		DependencyIndexes: file_payment_payment_proto_depIdxs,
		MessageInfos:      file_payment_payment_proto_msgTypes,
	}.Build()
	File_payment_payment_proto = out.File
	file_payment_payment_proto_goTypes = nil
	file_payment_payment_proto_depIdxs = nil
}
