// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: payment/payment.proto

package payment

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PaymentService service

type PaymentService interface {
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...client.CallOption) (*Payment, error)
	ProcessPayment(ctx context.Context, in *ProcessPaymentRequest, opts ...client.CallOption) (*PaymentResult, error)
	GetPaymentStatus(ctx context.Context, in *GetPaymentStatusRequest, opts ...client.CallOption) (*Payment, error)
	RefundPayment(ctx context.Context, in *RefundPaymentRequest, opts ...client.CallOption) (*PaymentResult, error)
	GetPaymentByOrderId(ctx context.Context, in *GetPaymentByOrderIdRequest, opts ...client.CallOption) (*Payment, error)
}

type paymentService struct {
	c    client.Client
	name string
}

func NewPaymentService(name string, c client.Client) PaymentService {
	return &paymentService{
		c:    c,
		name: name,
	}
}

func (c *paymentService) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...client.CallOption) (*Payment, error) {
	req := c.c.NewRequest(c.name, "PaymentService.CreatePayment", in)
	out := new(Payment)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentService) ProcessPayment(ctx context.Context, in *ProcessPaymentRequest, opts ...client.CallOption) (*PaymentResult, error) {
	req := c.c.NewRequest(c.name, "PaymentService.ProcessPayment", in)
	out := new(PaymentResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentService) GetPaymentStatus(ctx context.Context, in *GetPaymentStatusRequest, opts ...client.CallOption) (*Payment, error) {
	req := c.c.NewRequest(c.name, "PaymentService.GetPaymentStatus", in)
	out := new(Payment)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentService) RefundPayment(ctx context.Context, in *RefundPaymentRequest, opts ...client.CallOption) (*PaymentResult, error) {
	req := c.c.NewRequest(c.name, "PaymentService.RefundPayment", in)
	out := new(PaymentResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentService) GetPaymentByOrderId(ctx context.Context, in *GetPaymentByOrderIdRequest, opts ...client.CallOption) (*Payment, error) {
	req := c.c.NewRequest(c.name, "PaymentService.GetPaymentByOrderId", in)
	out := new(Payment)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PaymentService service

type PaymentServiceHandler interface {
	CreatePayment(context.Context, *CreatePaymentRequest, *Payment) error
	ProcessPayment(context.Context, *ProcessPaymentRequest, *PaymentResult) error
	GetPaymentStatus(context.Context, *GetPaymentStatusRequest, *Payment) error
	RefundPayment(context.Context, *RefundPaymentRequest, *PaymentResult) error
	GetPaymentByOrderId(context.Context, *GetPaymentByOrderIdRequest, *Payment) error
}

func RegisterPaymentServiceHandler(s server.Server, hdlr PaymentServiceHandler, opts ...server.HandlerOption) error {
	type paymentService interface {
		CreatePayment(ctx context.Context, in *CreatePaymentRequest, out *Payment) error
		ProcessPayment(ctx context.Context, in *ProcessPaymentRequest, out *PaymentResult) error
		GetPaymentStatus(ctx context.Context, in *GetPaymentStatusRequest, out *Payment) error
		RefundPayment(ctx context.Context, in *RefundPaymentRequest, out *PaymentResult) error
		GetPaymentByOrderId(ctx context.Context, in *GetPaymentByOrderIdRequest, out *Payment) error
	}
	type PaymentService struct {
		paymentService
	}
	h := &paymentServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&PaymentService{h}, opts...))
}

type paymentServiceHandler struct {
	PaymentServiceHandler
}

func (h *paymentServiceHandler) CreatePayment(ctx context.Context, in *CreatePaymentRequest, out *Payment) error {
	return h.PaymentServiceHandler.CreatePayment(ctx, in, out)
}

func (h *paymentServiceHandler) ProcessPayment(ctx context.Context, in *ProcessPaymentRequest, out *PaymentResult) error {
	return h.PaymentServiceHandler.ProcessPayment(ctx, in, out)
}

func (h *paymentServiceHandler) GetPaymentStatus(ctx context.Context, in *GetPaymentStatusRequest, out *Payment) error {
	return h.PaymentServiceHandler.GetPaymentStatus(ctx, in, out)
}

func (h *paymentServiceHandler) RefundPayment(ctx context.Context, in *RefundPaymentRequest, out *PaymentResult) error {
	return h.PaymentServiceHandler.RefundPayment(ctx, in, out)
}

func (h *paymentServiceHandler) GetPaymentByOrderId(ctx context.Context, in *GetPaymentByOrderIdRequest, out *Payment) error {
	return h.PaymentServiceHandler.GetPaymentByOrderId(ctx, in, out)
}
