// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user/user.proto

package user

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*AuthResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*AuthResponse, error)
	SendVerificationCode(ctx context.Context, in *SendCodeRequest, opts ...client.CallOption) (*CommonResponse, error)
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...client.CallOption) (*UserProfile, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...client.CallOption) (*CommonResponse, error)
	GetUserPreferences(ctx context.Context, in *GetPreferencesRequest, opts ...client.CallOption) (*UserPreferences, error)
	UpdateUserPreferences(ctx context.Context, in *UpdatePreferencesRequest, opts ...client.CallOption) (*CommonResponse, error)
	GetAddress(ctx context.Context, in *GetAddressRequest, opts ...client.CallOption) (*Address, error)
	ListAddresses(ctx context.Context, in *ListAddressesRequest, opts ...client.CallOption) (*AddressListResponse, error)
	CreateAddress(ctx context.Context, in *CreateAddressRequest, opts ...client.CallOption) (*Address, error)
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...client.CallOption) (*ValidateTokenResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*AuthResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.Register", in)
	out := new(AuthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*AuthResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.Login", in)
	out := new(AuthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SendVerificationCode(ctx context.Context, in *SendCodeRequest, opts ...client.CallOption) (*CommonResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.SendVerificationCode", in)
	out := new(CommonResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...client.CallOption) (*UserProfile, error) {
	req := c.c.NewRequest(c.name, "UserService.GetProfile", in)
	out := new(UserProfile)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...client.CallOption) (*CommonResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.UpdateProfile", in)
	out := new(CommonResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserPreferences(ctx context.Context, in *GetPreferencesRequest, opts ...client.CallOption) (*UserPreferences, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUserPreferences", in)
	out := new(UserPreferences)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UpdateUserPreferences(ctx context.Context, in *UpdatePreferencesRequest, opts ...client.CallOption) (*CommonResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.UpdateUserPreferences", in)
	out := new(CommonResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetAddress(ctx context.Context, in *GetAddressRequest, opts ...client.CallOption) (*Address, error) {
	req := c.c.NewRequest(c.name, "UserService.GetAddress", in)
	out := new(Address)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) ListAddresses(ctx context.Context, in *ListAddressesRequest, opts ...client.CallOption) (*AddressListResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.ListAddresses", in)
	out := new(AddressListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CreateAddress(ctx context.Context, in *CreateAddressRequest, opts ...client.CallOption) (*Address, error) {
	req := c.c.NewRequest(c.name, "UserService.CreateAddress", in)
	out := new(Address)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...client.CallOption) (*ValidateTokenResponse, error) {
	req := c.c.NewRequest(c.name, "UserService.ValidateToken", in)
	out := new(ValidateTokenResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	Register(context.Context, *RegisterRequest, *AuthResponse) error
	Login(context.Context, *LoginRequest, *AuthResponse) error
	SendVerificationCode(context.Context, *SendCodeRequest, *CommonResponse) error
	GetProfile(context.Context, *GetProfileRequest, *UserProfile) error
	UpdateProfile(context.Context, *UpdateProfileRequest, *CommonResponse) error
	GetUserPreferences(context.Context, *GetPreferencesRequest, *UserPreferences) error
	UpdateUserPreferences(context.Context, *UpdatePreferencesRequest, *CommonResponse) error
	GetAddress(context.Context, *GetAddressRequest, *Address) error
	ListAddresses(context.Context, *ListAddressesRequest, *AddressListResponse) error
	CreateAddress(context.Context, *CreateAddressRequest, *Address) error
	ValidateToken(context.Context, *ValidateTokenRequest, *ValidateTokenResponse) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		Register(ctx context.Context, in *RegisterRequest, out *AuthResponse) error
		Login(ctx context.Context, in *LoginRequest, out *AuthResponse) error
		SendVerificationCode(ctx context.Context, in *SendCodeRequest, out *CommonResponse) error
		GetProfile(ctx context.Context, in *GetProfileRequest, out *UserProfile) error
		UpdateProfile(ctx context.Context, in *UpdateProfileRequest, out *CommonResponse) error
		GetUserPreferences(ctx context.Context, in *GetPreferencesRequest, out *UserPreferences) error
		UpdateUserPreferences(ctx context.Context, in *UpdatePreferencesRequest, out *CommonResponse) error
		GetAddress(ctx context.Context, in *GetAddressRequest, out *Address) error
		ListAddresses(ctx context.Context, in *ListAddressesRequest, out *AddressListResponse) error
		CreateAddress(ctx context.Context, in *CreateAddressRequest, out *Address) error
		ValidateToken(ctx context.Context, in *ValidateTokenRequest, out *ValidateTokenResponse) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) Register(ctx context.Context, in *RegisterRequest, out *AuthResponse) error {
	return h.UserServiceHandler.Register(ctx, in, out)
}

func (h *userServiceHandler) Login(ctx context.Context, in *LoginRequest, out *AuthResponse) error {
	return h.UserServiceHandler.Login(ctx, in, out)
}

func (h *userServiceHandler) SendVerificationCode(ctx context.Context, in *SendCodeRequest, out *CommonResponse) error {
	return h.UserServiceHandler.SendVerificationCode(ctx, in, out)
}

func (h *userServiceHandler) GetProfile(ctx context.Context, in *GetProfileRequest, out *UserProfile) error {
	return h.UserServiceHandler.GetProfile(ctx, in, out)
}

func (h *userServiceHandler) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, out *CommonResponse) error {
	return h.UserServiceHandler.UpdateProfile(ctx, in, out)
}

func (h *userServiceHandler) GetUserPreferences(ctx context.Context, in *GetPreferencesRequest, out *UserPreferences) error {
	return h.UserServiceHandler.GetUserPreferences(ctx, in, out)
}

func (h *userServiceHandler) UpdateUserPreferences(ctx context.Context, in *UpdatePreferencesRequest, out *CommonResponse) error {
	return h.UserServiceHandler.UpdateUserPreferences(ctx, in, out)
}

func (h *userServiceHandler) GetAddress(ctx context.Context, in *GetAddressRequest, out *Address) error {
	return h.UserServiceHandler.GetAddress(ctx, in, out)
}

func (h *userServiceHandler) ListAddresses(ctx context.Context, in *ListAddressesRequest, out *AddressListResponse) error {
	return h.UserServiceHandler.ListAddresses(ctx, in, out)
}

func (h *userServiceHandler) CreateAddress(ctx context.Context, in *CreateAddressRequest, out *Address) error {
	return h.UserServiceHandler.CreateAddress(ctx, in, out)
}

func (h *userServiceHandler) ValidateToken(ctx context.Context, in *ValidateTokenRequest, out *ValidateTokenResponse) error {
	return h.UserServiceHandler.ValidateToken(ctx, in, out)
}
